Final task
PutskouDzmitry/JWT pull request #1
Opened 2021-07-01 13:10 UTC by PutskouDzmitry

2021-07-01 14:19 UTC, renort requested changes

2021-07-01 14:19 UTC, renort commented on pkg/struct/book.go
> +package _struct
неудачное название, т.к. struct ключевое слово языка, переименуй в entity

2021-07-01 14:19 UTC, renort commented on pkg/repository/authMongo.go
> +	err := a.redis.Set("Access_token", token, time.Minute * 30).Err()
это будет работать если пользователей несколько? я предполагаю должно быть так Redis.Get(fmt.Sprintf("Access_token-%d", userID))

2021-07-01 14:19 UTC, renort commented on pkg/repository/redis.go
> +		Addr: "localhost:6379",
переменные окружения

2021-07-01 14:19 UTC, renort commented on pkg/repository/redis.go
> +	_, err := client.Ping().Result()
нужно добавить backoff

2021-07-01 14:19 UTC, renort commented on docker-compose.yaml
> +
redis тоже должен подниматься в контейнере

2021-07-01 14:19 UTC, renort commented on docker-compose.yaml
> +    networks:
добавь healthcheck, т.к. depends_on не гарантирует что приложение стартует после базы(контейнер с бд может быть поднят но бд в контейнере может понадобиться некоторое время чтобы запуститься)
Пример здесь: https://stackoverflow.com/questions/54384042/why-does-the-docker-compose-healthcheck-of-my-mongo-container-always-fail

2021-07-01 14:19 UTC, renort commented on pkg/repository/authMongo.go
> +	return token, nil
зачем возвращать исходное значение если внутри функции оно не модифицируется?

2021-07-01 14:19 UTC, renort commented on pkg/repository/repository.go
> +	SetAccessToken(token string) (string, error)
функции сеттеры в данном случае должны выглядеть так: SetAccessToken(token string) (error)

2021-07-01 15:29 UTC, PutskouDzmitry commented on pkg/struct/book.go
> +package _struct
completed

2021-07-01 15:29 UTC, PutskouDzmitry commented on pkg/repository/redis.go
> +		Addr: "localhost:6379",
completed

2021-07-01 15:29 UTC, PutskouDzmitry commented on pkg/repository/redis.go
> +	_, err := client.Ping().Result()
completed

2021-07-01 16:21 UTC, PutskouDzmitry commented on pkg/repository/authMongo.go
> +	return token, nil
completed

2021-07-01 16:21 UTC, PutskouDzmitry commented on pkg/repository/repository.go
> +	SetAccessToken(token string) (string, error)
completed

2021-07-01 16:21 UTC, PutskouDzmitry commented on docker-compose.yaml
> +    networks:
completed

2021-07-01 16:21 UTC, PutskouDzmitry commented on docker-compose.yaml
> +
completed

2021-07-01 16:21 UTC, PutskouDzmitry commented on pkg/repository/authMongo.go
> +	err := a.redis.Set("Access_token", token, time.Minute * 30).Err()
completed

2021-07-02 07:58 UTC, renort requested changes

2021-07-02 07:58 UTC, renort commented on docker-compose.yaml
> +      interval: ${REDIS_INTERVAL}
Нужно еще указать команду test, вот пример 
healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

2021-07-02 07:58 UTC, renort commented on pkg/repository/bookMongo.go
> +	_struct "github.com/PutskouDzmitry/golang-training-Library/pkg/entity"
убери _struct

2021-07-02 07:58 UTC, renort commented on pkg/service/auth.go
> +	refreshToken, err := s.repo.GetRefreshToken(token, "qwe")
?!

2021-07-02 07:58 UTC, renort commented on pkg/service/book.go
> +	_struct "github.com/PutskouDzmitry/golang-training-Library/pkg/entity"
убери _struct

2021-07-02 08:12 UTC, PutskouDzmitry commented on docker-compose.yaml
> +      interval: ${REDIS_INTERVAL}
completed

2021-07-02 08:12 UTC, PutskouDzmitry commented on pkg/repository/bookMongo.go
> +	_struct "github.com/PutskouDzmitry/golang-training-Library/pkg/entity"
completed

2021-07-02 08:12 UTC, PutskouDzmitry commented on pkg/service/auth.go
> +	refreshToken, err := s.repo.GetRefreshToken(token, "qwe")
completed

2021-07-02 08:12 UTC, PutskouDzmitry commented on pkg/service/book.go
> +	_struct "github.com/PutskouDzmitry/golang-training-Library/pkg/entity"
completed

2021-07-02 09:12 UTC, renort approved these changes

2021-07-02 09:13 UTC, merged